apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: workload-cluster
spec:
  deletionPolicy: Delete
  forProvider:
    initialClusterVersion: latest
    location: asia-south1-a
    loggingService: none
    monitoringService: none
  writeConnectionSecretToRef:
    name: workload-cluster-creds
    namespace: default
